/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package decodificarcodigoqr;

import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author jjsc
 */
public class PanelLogo extends javax.swing.JPanel {
    private String imagenNombre;
    
    public PanelLogo() {
        initComponents();
    }
    
     public PanelLogo(String nombre) {
        initComponents();
        imagenNombre = nombre;
    }

    public String getImagenNombre() {
        return imagenNombre;
    }

    public void setImagenNombre(String imagenNombre) {
        this.imagenNombre = imagenNombre;
    }
    
    

    @Override
    public void paint(Graphics g){
       String ruta = imagenNombre; //System.getProperty("user.dir")+"/imagenes/"+imagenNombre;
       ImageIcon imagenFondo = new ImageIcon(ruta);                     
       g.drawImage(imagenFondo.getImage(),0,0,getWidth(),getHeight(), null);                
       setOpaque(false);
       super.paintComponent(g);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
